### PR TITLE
Force Dark theme with OLED

### PR DESCRIPTION
**Pull request by Monochromish**
This PR forces the Annie dark theme no matter what system theme is set.
This is not perfect, but I have tried my best to override most broken places I could find. 

* Here are a few preview images for the same (with light mode turned on):

image
image

* Here are a few preview images for the same (with light mode turned off):

image
image

Spent some good amount of time on this give me bobux

### CODE REVIEW

**Comment by yazninja** [comment]
modals, like when u try to install a theme

**Comment by Monochromish** [comment]
Worked on them too

**Comment by Monochromish** [comment]
image
image

**Comment by Monochromish** [comment]
Preview (light mode turned on):

image
image

**Comment by yazninja** [comment]
Great!, i just have one request, pls change the color of the theme packs, its so that we know what is the theme and the pack inside
[image](https://user-images.githubusercontent.com/71800112/177753849-81ca0630-02a1-4772-94b6-bcb2fdc4cc7c.png)

**Comment by Monochromish** [comment]
@yazninja ...

**Comment by yazninja** [comment]
nice it shall be merged

**Pull request merged**
